/**
 * Realistic Mock Data for Officer Command Dashboard
 * Zonal Field Officer: Kalai (Ward 14 - Indiranagar, East Zone)
 */

export const INITIAL_OFFICER_COMPLAINTS = [
  {
    id: 'CC-9041',
    title: 'Dangerous Deep Pothole on 100ft Road Junction',
    category: 'Roads & Potholes',
    description: 'A 2-foot wide and 6-inch deep crater has formed near the junction traffic light after recent rains, posing severe hazard to two-wheeler riders.',
    location: '100ft Road, Near KFC Junction, Indiranagar',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9784, 77.6408],
    priority: 'High',
    urgencyScore: 95,
    status: 'In Progress',
    reportedDate: '2026-08-23 07:45 AM',
    slaDeadline: '4 Hours Remaining',
    slaHoursLeft: 4,
    reportedBy: {
      name: 'Rohan Sharma',
      phone: '+91 98450 12345',
      address: '14/B, 12th Main Road, Indiranagar',
    },
    assignedTeam: 'BBMP Rapid Road Repair Unit 2',
    beforeImage: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: 'Asphalt patching crew dispatched with hot-mix truck at 09:15 AM. Work in progress.',
    timeline: [
      { timestamp: '07:45 AM', action: 'Reported by Citizen', user: 'Rohan Sharma', note: 'AI classified as High Priority (Score: 95)' },
      { timestamp: '08:10 AM', action: 'Assigned to Zonal Officer', user: 'Auto-Routing AI', note: 'Assigned to Officer Kalai (Ward 14)' },
      { timestamp: '09:15 AM', action: 'Field Crew Dispatched', user: 'Officer Kalai', note: 'BBMP Rapid Road Repair Unit 2 assigned' },
    ],
  },
  {
    id: 'CC-8920',
    title: 'Overflowing Commercial Garbage Dumpster',
    category: 'Garbage & Sanitation',
    description: 'Municipal waste bin overflowing onto the pedestrian footpath. Foul smell and stray animal congregation near residential apartments.',
    location: '4th Cross, Near BDA Complex, Ward 14',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9750, 77.6420],
    priority: 'High',
    urgencyScore: 91,
    status: 'Pending',
    reportedDate: '2026-08-23 06:30 AM',
    slaDeadline: '2 Hours Remaining',
    slaHoursLeft: 2,
    reportedBy: {
      name: 'Priya Narayanan',
      phone: '+91 97312 98765',
      address: 'Apt 302, Greenview Heights, 4th Cross',
    },
    assignedTeam: 'Solid Waste Sanitation Team 4',
    beforeImage: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: '',
    timeline: [
      { timestamp: '06:30 AM', action: 'Reported by Citizen', user: 'Priya Narayanan', note: 'Citizen flagged sanitation hazard' },
      { timestamp: '07:00 AM', action: 'Verification Pending', user: 'System', note: 'Awaiting officer field inspection' },
    ],
  },
  {
    id: 'CC-8812',
    title: 'Underground Drinking Water Pipeline Leak & Flooding',
    category: 'Water Supply',
    description: 'Major potable water supply line burst causing continuous flooding on the street and low water pressure to surrounding blocks.',
    location: 'CMH Road, Near Metro Pillar 118',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9802, 77.6385],
    priority: 'High',
    urgencyScore: 89,
    status: 'In Progress',
    reportedDate: '2026-08-22 05:15 PM',
    slaDeadline: '1 Hour Remaining',
    slaHoursLeft: 1,
    reportedBy: {
      name: 'K. Venkatesh',
      phone: '+91 94480 34567',
      address: 'Shop #12, CMH Road Commercial Block',
    },
    assignedTeam: 'BWSSB Water Emergency Squad',
    beforeImage: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: 'Valve isolated to stop wastage. Excavation team replacing cracked 4-inch PVC sleeve.',
    timeline: [
      { timestamp: '05:15 PM (Yesterday)', action: 'Reported', user: 'K. Venkatesh', note: 'Water gushing on main road' },
      { timestamp: '06:00 PM', action: 'Status changed to In Progress', user: 'Officer Kalai', note: 'Main valve isolated' },
    ],
  },
  {
    id: 'CC-8755',
    title: 'Broken LED Streetlight Pole #42 at 12th Main',
    category: 'Electrical & Lighting',
    description: 'Streetlight completely unlit for 3 nights. High risk area for pedestrian safety and night commute.',
    location: '12th Main Road, HAL 2nd Stage',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9765, 77.6465],
    priority: 'Medium',
    urgencyScore: 74,
    status: 'Resolved',
    reportedDate: '2026-08-22 11:20 AM',
    slaDeadline: 'Resolved within SLA',
    slaHoursLeft: 0,
    reportedBy: {
      name: 'Sunita Rao',
      phone: '+91 98860 88776',
      address: '88, 12th Main Road, Indiranagar',
    },
    assignedTeam: 'BESCOM Electrical Line Crew 3',
    beforeImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    proofImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    officerNotes: 'Replaced faulty 80W LED luminaire fixture and checked grounding wire. Fully illuminated and verified on-site.',
    timeline: [
      { timestamp: '11:20 AM (Aug 22)', action: 'Reported', user: 'Sunita Rao', note: 'Street dark' },
      { timestamp: '02:00 PM', action: 'In Progress', user: 'Officer Kalai', note: 'Electrician dispatched' },
      { timestamp: '05:40 PM', action: 'Resolved', user: 'Officer Kalai', note: 'LED luminaire replaced with proof' },
    ],
  },
  {
    id: 'CC-8640',
    title: 'Blocked Stormwater Drain Causing Waterlogging',
    category: 'Drainage & Sewage',
    description: 'Monsoon drain inlet clogged with plastic debris and construction silt. Water accumulates up to knee depth after showers.',
    location: '6th Main Road, Ward 14, Indiranagar',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9715, 77.6410],
    priority: 'High',
    urgencyScore: 88,
    status: 'Pending',
    reportedDate: '2026-08-23 08:15 AM',
    slaDeadline: '5 Hours Remaining',
    slaHoursLeft: 5,
    reportedBy: {
      name: 'Arun Varma',
      phone: '+91 99001 23456',
      address: 'Flat 101, Palm Court, 6th Main',
    },
    assignedTeam: 'Stormwater Desilting Squad',
    beforeImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: '',
    timeline: [
      { timestamp: '08:15 AM', action: 'Reported by Citizen', user: 'Arun Varma', note: 'Drainage blockage flagged' },
    ],
  },
  {
    id: 'CC-8532',
    title: 'Fallen Tree Branch Obstructing Single-Lane Alley',
    category: 'Parks & Horticulture',
    description: 'Heavy rain caused large eucalyptus branch to snap and block vehicular access to 4 residential villas.',
    location: 'Defence Colony 6th A Cross, Ward 14',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9820, 77.6440],
    priority: 'Medium',
    urgencyScore: 68,
    status: 'Resolved',
    reportedDate: '2026-08-22 09:00 AM',
    slaDeadline: 'Resolved within SLA',
    slaHoursLeft: 0,
    reportedBy: {
      name: 'Col. Ranjit Roy',
      phone: '+91 98440 55667',
      address: 'Villa 12, Defence Colony',
    },
    assignedTeam: 'Forestry & Horticulture Rapid Unit',
    beforeImage: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&auto=format&fit=crop&q=80',
    proofImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
    officerNotes: 'Branch sectioned with chainsaw and carted away. Road cleared for full two-way traffic.',
    timeline: [
      { timestamp: '09:00 AM (Aug 22)', action: 'Reported', user: 'Col. Ranjit Roy', note: 'Access blocked' },
      { timestamp: '11:30 AM', action: 'Resolved', user: 'Officer Kalai', note: 'Debris cleared with proof photo' },
    ],
  },
  {
    id: 'CC-8421',
    title: 'Missing Manhole Cover Near Primary School',
    category: 'Drainage & Sewage',
    description: 'Cast iron manhole lid missing. Highly dangerous for school children during morning and evening rush.',
    location: '80 Feet Road, Near St. Joseph School',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9730, 77.6350],
    priority: 'High',
    urgencyScore: 98,
    status: 'In Progress',
    reportedDate: '2026-08-23 06:00 AM',
    slaDeadline: '1 Hour Remaining',
    slaHoursLeft: 1,
    reportedBy: {
      name: 'Deepak Chandran',
      phone: '+91 98800 11223',
      address: 'PTA Committee, St. Joseph School',
    },
    assignedTeam: 'BBMP Engineering Rapid Team',
    beforeImage: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: 'Temporary safety barricade with caution tape placed at 06:45 AM. Heavy duty concrete replacement cover being installed.',
    timeline: [
      { timestamp: '06:00 AM', action: 'Critical Alert Reported', user: 'Deepak Chandran', note: 'AI Urgency Score: 98 (Top Priority)' },
      { timestamp: '06:45 AM', action: 'Safety Barricade Erected', user: 'Officer Kalai', note: 'Hazard secured' },
    ],
  },
  {
    id: 'CC-8310',
    title: 'Illegal Dumping of Commercial Debris in Empty Plot',
    category: 'Garbage & Sanitation',
    description: 'Truck dumped concrete debris and tiles overnight on vacant plot #24. Obstructing side drainage.',
    location: 'Double Road, Ward 14, Indiranagar',
    ward: 'Ward 14 (Indiranagar)',
    zone: 'East Zone',
    coordinates: [12.9790, 77.6480],
    priority: 'Low',
    urgencyScore: 45,
    status: 'Pending',
    reportedDate: '2026-08-23 09:10 AM',
    slaDeadline: '24 Hours Remaining',
    slaHoursLeft: 24,
    reportedBy: {
      name: 'Sneha Patel',
      phone: '+91 97400 99881',
      address: 'House #45, Double Road',
    },
    assignedTeam: 'BBMP Marshals & Enforcement',
    beforeImage: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80',
    proofImage: null,
    officerNotes: '',
    timeline: [
      { timestamp: '09:10 AM', action: 'Reported', user: 'Sneha Patel', note: 'Debris dumping logged' },
    ],
  },
];

// Sample resolution proof photos for quick 1-click testing
export const SAMPLE_PROOF_PHOTOS = [
  {
    title: 'Road Asphalt Repaired & Compacted',
    url: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=600&auto=format&fit=crop&q=80',
    note: 'Cold-mix asphalt leveled and compacted to road gradient.',
  },
  {
    title: 'Garbage Bin Cleared & Sanitized',
    url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&auto=format&fit=crop&q=80',
    note: 'Container cleared by sanitation compactor and lime powder sprayed.',
  },
  {
    title: 'Water Pipe Welded & Sealed',
    url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
    note: 'Pipe collar fitted, pressure tested at 4.5 bar with zero leakage.',
  },
  {
    title: 'Streetlight Replacement Verified',
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    note: 'New energy-efficient luminaire working, verified on-site.',
  },
  {
    title: 'Drain Cleared & Desilted',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    note: 'Debris extracted and grates repositioned for smooth runoff.',
  },
];

export const OFFICER_PROFILE = {
  name: 'Kalai S.',
  role: 'Zonal Field Officer',
  ward: 'Ward 14 (Indiranagar)',
  zone: 'East Zone, BBMP',
  badgeNumber: 'BBMP-OFC-0842',
  phone: '+91 94480 88221',
  email: 'kalai.ward14@bbmp.gov.in',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  slaCompliance: '94.2%',
  avgResolutionHours: '3.6h',
};
